In [2]:
import pandas as pd 
import numpy as np 
import matplotlib as plt

In [3]:
# Load CSV Files 

## Black Homeowners
file_id = "11389zmsdjnnpT7BdABWrEIKiyUZMRLdi"
url = f"https://drive.google.com/uc?export=download&id={file_id}"
black_homeowners = pd.read_csv(url)

## Disaster Declarations 
file_id = "1-tvryFXhivyt3AFDV0CDR2GmHgiMZuAZ"
url = f"https://drive.google.com/uc?export=download&id={file_id}"
disaster_dec = pd.read_csv(url)

## HMA Projects 
file_id = "10Qdne5nzy36pfl4cejNpqmQ9crCJOQ-z"
url = f"https://drive.google.com/uc?export=download&id={file_id}"
hma_p = pd.read_csv(url)

# HMA Project Communities 
file_id = "101oHQho4hLTlVmzcRZ1Pkf5V4WfVL5NB"
url = f"https://drive.google.com/uc?export=download&id={file_id}"
hma_pc = pd.read_csv(url)

/var/folders/kb/k7mr1yyx1yd_xnw2fpjp95l40000gn/T/ipykernel_18318/4191518867.py:11: DtypeWarning: Columns (21) have mixed types. Specify dtype option on import or set low_memory=False.
  disaster_dec = pd.read_csv(url)

# Black Homeowners Data

In [4]:
# Black Homeowners
black_homeowners.head()

,geo_level,geo_name,year,state_name,pct_black_alone,pct_owner_occupied_black_alone,rpl_themes,quartiles_rpl_themes
0,county,"Barbour County, West Virginia",2023,West Virginia,1.8,0.0,0.456,26-50% of geographies
1,county,"Alexander County, North Carolina",2023,North Carolina,4.0,2.0,0.456,26-50% of geographies
2,county,"Jackson County, Indiana",2023,Indiana,1.1,0.4,0.456,26-50% of geographies
3,county,"York County, South Carolina",2023,South Carolina,18.7,13.0,0.344,26-50% of geographies
4,county,"Clinton County, Indiana",2023,Indiana,0.7,0.0,0.344,26-50% of geographies

In [5]:
black_homeowners.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3144 entries, 0 to 3143
Data columns (total 8 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   geo_level                       3144 non-null   object
 1   geo_name                        3144 non-null   object
 2   year                            3144 non-null   int64
 3   state_name                      3144 non-null   object
 4   pct_black_alone                 3144 non-null   float64
 5   pct_owner_occupied_black_alone  3143 non-null   float64
 6   rpl_themes                      3144 non-null   float64
 7   quartiles_rpl_themes            3144 non-null   object
dtypes: float64(3), int64(1), object(4)
memory usage: 196.6+ KB

# Disaster Declarations Data

In [6]:
# Disaster Declarations
disaster_dec.head()

,femaDeclarationString,disasterNumber,state,declarationType,declarationDate,fyDeclared,incidentType,declarationTitle,ihProgramDeclared,iaProgramDeclared,...,placeCode,designatedArea,declarationRequestNumber,lastIAFilingDate,incidentId,region,designatedIncidentTypes,lastRefresh,hash,id
0,FM-5529-OR,5529,OR,FM,2024-08-09T00:00:00.000Z,2024,Fire,LEE FALLS FIRE,0,0,...,99067,Washington (County),24122,NaN,2024081001,10,R,2024-08-27T18:22:14.800Z,ae87cf3c6ed795015b714af7166c7c295b2b67c7,09e3f81a-5e16-4b72-b317-1c64e0cfa59c
1,FM-5528-OR,5528,OR,FM,2024-08-06T00:00:00.000Z,2024,Fire,ELK LANE FIRE,0,0,...,99031,Jefferson (County),24116,NaN,2024080701,10,R,2024-08-27T18:22:14.800Z,432cf0995c47e3895cea696ede5621b810460501,59983f89-30bf-4888-b21b-62e8d57d9aac
2,FM-5527-OR,5527,OR,FM,2024-08-02T00:00:00.000Z,2024,Fire,MILE MARKER 132 FIRE,0,0,...,99017,Deschutes (County),24111,NaN,2024080301,10,R,2024-08-27T18:22:14.800Z,2f21d90cb6bc64b0d4121aa3f18d852bbb4b11fa,8d13ecf0-bc2f-496b-8c9f-b2e73da832a0
3,DR-4312-CA,4312,CA,DR,2017-05-02T00:00:00.000Z,2017,Severe Storm,FLOODING,0,0,...,60347,Resighini Rancheria (Indian Reservation),17035,NaN,2017041001,9,NaN,2025-03-26T20:21:32.579Z,432a3a64bdbb291ae26cf5a27a33deeabb380481,98a7c5bb-2346-45aa-a1ca-0399440d4f0b
4,DR-4251-AL,4251,AL,DR,2016-01-21T00:00:00.000Z,2016,Severe Storm,"SEVERE STORMS, TORNADOES, STRAIGHT-LINE WINDS,...",0,0,...,99001,Autauga (County),16003,NaN,2015122301,4,NaN,2025-03-27T12:21:46.559Z,dcd4ce6b37ee49875b3f1e32e9a8a16cd6a803d3,5229bbae-eee6-42b8-b277-edbafa8d6cb2

In [7]:
disaster_dec.shape

(68248, 28)

In [8]:
# Get column names
print("Column Names:")
print(disaster_dec.columns.values)

# Null Values 
print(" Null Values Count")
disaster_dec.isna().sum()

Column Names:
['femaDeclarationString' 'disasterNumber' 'state' 'declarationType'
 'declarationDate' 'fyDeclared' 'incidentType' 'declarationTitle'
 'ihProgramDeclared' 'iaProgramDeclared' 'paProgramDeclared'
 'hmProgramDeclared' 'incidentBeginDate' 'incidentEndDate'
 'disasterCloseoutDate' 'tribalRequest' 'fipsStateCode' 'fipsCountyCode'
 'placeCode' 'designatedArea' 'declarationRequestNumber'
 'lastIAFilingDate' 'incidentId' 'region' 'designatedIncidentTypes'
 'lastRefresh' 'hash' 'id']
 Null Values Count

femaDeclarationString           0
disasterNumber                  0
state                           0
declarationType                 0
declarationDate                 0
fyDeclared                      0
incidentType                    0
declarationTitle                0
ihProgramDeclared               0
iaProgramDeclared               0
paProgramDeclared               0
hmProgramDeclared               0
incidentBeginDate               0
incidentEndDate               612
disasterCloseoutDate        15855
tribalRequest                   0
fipsStateCode                   0
fipsCountyCode                  0
placeCode                       0
designatedArea                  0
declarationRequestNumber        0
lastIAFilingDate            48969
incidentId                      0
region                          0
designatedIncidentTypes     47812
lastRefresh                     0
hash                            0
id                              0
dtype: int64

In [9]:
# Identify columns with 'date' in the name 
date_cols = [col for col in disaster_dec.columns if 'date' in col.lower()]

# Convert those columns to datetime format
for col in date_cols:
    disaster_dec[col] = pd.to_datetime(disaster_dec[col], errors='coerce')

print("Converted the following columns to datetime:")
print(date_cols)

Converted the following columns to datetime:
['declarationDate', 'incidentBeginDate', 'incidentEndDate', 'disasterCloseoutDate', 'lastIAFilingDate']

In [10]:
# Drop unecessary columns
disaster_dec = disaster_dec.drop(columns=["lastIAFilingDate"]) # too many missing values (more than half of dataset)
disaster_dec = disaster_dec.drop(columns=["lastRefresh"]) # not relevant to analysis
disaster_dec = disaster_dec.drop(columns=['designatedIncidentTypes']) 

# delete null values for disasterCloseoutDate  
disaster_dec = disaster_dec.dropna(subset=['incidentEndDate']) # very few missing values, won't impact much of the dataset 
disaster_dec = disaster_dec.dropna(subset=['disasterCloseoutDate']) # same

In [11]:
disaster_dec.isna().sum()

femaDeclarationString       0
disasterNumber              0
state                       0
declarationType             0
declarationDate             0
fyDeclared                  0
incidentType                0
declarationTitle            0
ihProgramDeclared           0
iaProgramDeclared           0
paProgramDeclared           0
hmProgramDeclared           0
incidentBeginDate           0
incidentEndDate             0
disasterCloseoutDate        0
tribalRequest               0
fipsStateCode               0
fipsCountyCode              0
placeCode                   0
designatedArea              0
declarationRequestNumber    0
incidentId                  0
region                      0
hash                        0
id                          0
dtype: int64

In [12]:
disaster_dec.shape

(51967, 25)

# HMA Projects Data

In [13]:
hma_p.head()

,projectIdentifier,programArea,programFy,region,state,stateNumberCode,county,countyCode,disasterNumber,projectCounties,...,federalShareObligated,subrecipientAdminCostAmt,srmcObligatedAmt,recipientAdminCostAmt,costSharePercentage,benefitCostRatio,netValueBenefits,numberOfFinalProperties,numberOfProperties,id
0,DR-4251-0005-R,HMGP,2016,4,Alabama,1,Jackson,71.0,4251.0,JACKSON,...,65654.55,0.0,0.0,0.0,0.75,7.21,1012105.0,1,1,ae94ca36-60cd-4e39-a2ee-c2b6aa2396e9
1,DR-4214-0018-R,HMGP,2015,1,Massachusetts,25,Norfolk,21.0,4214.0,NORFOLK,...,965190.69,0.0,0.0,0.0,0.75,3.21,4008777.0,4,6,628d7c32-00b1-4f5d-9cf5-b8958447612a
2,DR-4283-0027-R,HMGP,2017,4,Florida,12,Flagler,35.0,4283.0,FLAGLER,...,241847.25,0.0,0.0,0.0,0.75,2.36,824905.0,0,0,f170bb61-976f-4df7-b049-27050c6b5862
3,DR-4223-0096,HMGP,2015,6,Texas,48,Jefferson,245.0,4223.0,JEFFERSON,...,NaN,NaN,NaN,NaN,0.75,1.13,735469.0,0,1,6ffb1aa6-efe2-4c53-8429-42470b96ef41
4,DR-4241-0059,HMGP,2016,4,South Carolina,45,Dorchester,35.0,4241.0,DORCHESTER,...,NaN,NaN,NaN,NaN,0.00,1.08,464354.0,0,0,32f51750-f820-4a66-93fa-c148dd9c937d

In [14]:
hma_p.shape

(53439, 33)

In [15]:
hma_p.columns.values

array(['projectIdentifier', 'programArea', 'programFy', 'region', 'state',
       'stateNumberCode', 'county', 'countyCode', 'disasterNumber',
       'projectCounties', 'projectType', 'status', 'recipient',
       'recipientTribalIndicator', 'subrecipient',
       'subrecipientTribalIndicator', 'dataSource', 'dateApproved',
       'dateClosed', 'dateInitiallyApproved', 'projectAmount',
       'initialObligationDate', 'initialObligationAmount',
       'federalShareObligated', 'subrecipientAdminCostAmt',
       'srmcObligatedAmt', 'recipientAdminCostAmt', 'costSharePercentage',
       'benefitCostRatio', 'netValueBenefits', 'numberOfFinalProperties',
       'numberOfProperties', 'id'], dtype=object)

In [16]:
hma_p.isna().sum()

projectIdentifier                  0
programArea                        0
programFy                          0
region                             0
state                              0
stateNumberCode                    0
county                          3366
countyCode                      3366
disasterNumber                 12862
projectCounties                 3018
projectType                      491
status                            97
recipient                       9727
recipientTribalIndicator        9727
subrecipient                     802
subrecipientTribalIndicator     9727
dataSource                         0
dateApproved                   14620
dateClosed                     17256
dateInitiallyApproved          23991
projectAmount                    886
initialObligationDate          22470
initialObligationAmount        22470
federalShareObligated          14127
subrecipientAdminCostAmt       29061
srmcObligatedAmt               29024
recipientAdminCostAmt          29061
costSharePercentage             1405
benefitCostRatio                7778
netValueBenefits                8441
numberOfFinalProperties            0
numberOfProperties                 0
id                                 0
dtype: int64

In [17]:
# check null values presence >50% 
missing_percent = hma_p.isna().mean().sort_values(ascending=False)
print(missing_percent.head(40))

subrecipientAdminCostAmt       0.543816
recipientAdminCostAmt          0.543816
srmcObligatedAmt               0.543124
dateInitiallyApproved          0.448942
initialObligationAmount        0.420479
initialObligationDate          0.420479
dateClosed                     0.322910
dateApproved                   0.273583
federalShareObligated          0.264357
disasterNumber                 0.240686
recipient                      0.182021
subrecipientTribalIndicator    0.182021
recipientTribalIndicator       0.182021
netValueBenefits               0.157956
benefitCostRatio               0.145549
countyCode                     0.062988
county                         0.062988
projectCounties                0.056476
costSharePercentage            0.026292
projectAmount                  0.016580
subrecipient                   0.015008
projectType                    0.009188
status                         0.001815
numberOfFinalProperties        0.000000
numberOfProperties             0.000000
projectIdentifier              0.000000
dataSource                     0.000000
programArea                    0.000000
stateNumberCode                0.000000
state                          0.000000
region                         0.000000
programFy                      0.000000
id                             0.000000
dtype: float64

In [18]:
# drop small number of null values (0.001%)
hma_p = hma_p.dropna(subset="status")

# drop unecessary columns 
hma_p = hma_p.drop(columns=['subrecipientTribalIndicator', 'subrecipientAdminCostAmt', 'srmcObligatedAmt', 'recipientAdminCostAmt','dateInitiallyApproved', 'initialObligationDate', 'initialObligationAmount', 'id', 'countyCode'])

hma_p.isna().sum()

projectIdentifier               0
programArea                     0
programFy                       0
region                          0
state                           0
stateNumberCode                 0
county                       3291
disasterNumber              12770
projectCounties              2943
projectType                   417
status                          0
recipient                    9630
recipientTribalIndicator     9630
subrecipient                  727
dataSource                      0
dateApproved                14533
dateClosed                  17161
projectAmount                 884
federalShareObligated       14125
costSharePercentage          1403
benefitCostRatio             7687
netValueBenefits             8350
numberOfFinalProperties         0
numberOfProperties              0
dtype: int64

In [19]:
hma_p.shape

(53342, 24)

In [20]:
# format projectCounties - lowercase 
hma_p['projectCounties'] = hma_p['projectCounties'].str.capitalize()
print(hma_p['projectCounties'])

0               Jackson
1               Norfolk
2               Flagler
3             Jefferson
4            Dorchester
              ...
53434            Goliad
53435         Ontonagon
53436         Highlands
53437    San bernardino
53438             Lamar
Name: projectCounties, Length: 53342, dtype: object

In [21]:
# Match County and projectCounties

def extract_clean_county(value):
    if isinstance(value, str):
        # Handle known messy entries
        if "Multiple" in value or "Various" in value:
            return None
        # Extract first entry
        first = value.split(',')[0]
        # Remove words like "County" or "Parish", clean whitespace
        return (
            first.replace("County", "")
                 .replace("Parish", "")
                 .strip()
        )
    return None

mask = hma_p['county'].isna() & hma_p['projectCounties'].notna()

hma_p.loc[mask, 'county'] = hma_p.loc[mask, 'projectCounties'].apply(extract_clean_county)
print("Remaining missing values in `county`:", hma_p['county'].isna().sum())

Remaining missing values in `county`: 2771

In [22]:
hma_p.isna().sum()

projectIdentifier               0
programArea                     0
programFy                       0
region                          0
state                           0
stateNumberCode                 0
county                       2771
disasterNumber              12770
projectCounties              2943
projectType                   417
status                          0
recipient                    9630
recipientTribalIndicator     9630
subrecipient                  727
dataSource                      0
dateApproved                14533
dateClosed                  17161
projectAmount                 884
federalShareObligated       14125
costSharePercentage          1403
benefitCostRatio             7687
netValueBenefits             8350
numberOfFinalProperties         0
numberOfProperties              0
dtype: int64

In [23]:
# Fill projectCounties with cleaned county names where it's missing
mask = hma_p['projectCounties'].isna() & hma_p['county'].notna()

hma_p.loc[mask, 'projectCounties'] = hma_p.loc[mask, 'county'] + " County"

hma_p.isna().sum()

projectIdentifier               0
programArea                     0
programFy                       0
region                          0
state                           0
stateNumberCode                 0
county                       2771
disasterNumber              12770
projectCounties              2745
projectType                   417
status                          0
recipient                    9630
recipientTribalIndicator     9630
subrecipient                  727
dataSource                      0
dateApproved                14533
dateClosed                  17161
projectAmount                 884
federalShareObligated       14125
costSharePercentage          1403
benefitCostRatio             7687
netValueBenefits             8350
numberOfFinalProperties         0
numberOfProperties              0
dtype: int64

In [24]:
# Fill categorical columns
hma_p['projectType'] = hma_p['projectType'].fillna('Unknown')
hma_p['recipient'] = hma_p['recipient'].fillna('Unknown')
hma_p['recipientTribalIndicator'] = hma_p['recipientTribalIndicator'].fillna(False)
hma_p['subrecipient'] = hma_p['subrecipient'].fillna('Unknown')
hma_p['county'] = hma_p['county'].fillna('Unknown')
hma_p['projectCounties'] = hma_p['projectCounties'].fillna('Unknown')

# Fill numeric columns
hma_p['projectAmount'] = hma_p['projectAmount'].fillna(0)
hma_p['costSharePercentage'] = hma_p['costSharePercentage'].fillna(75)
hma_p['benefitCostRatio'] = hma_p['benefitCostRatio'].fillna(hma_p['benefitCostRatio'].median())
hma_p['federalShareObligated'] = hma_p['federalShareObligated'].fillna(hma_p['federalShareObligated'].median())
hma_p['disasterNumber'] = hma_p['disasterNumber'].fillna(-1)

hma_p = hma_p.dropna(subset=['netValueBenefits'])

# hadling dates 
date_cols = [col for col in hma_p.columns if 'date' in col.lower()]

# Convert those columns to datetime format
for col in date_cols:
    hma_p[col] = pd.to_datetime(hma_p[col], errors='coerce')

print("Converted the following columns to datetime:")
print(date_cols)

hma_p['dateApproved'] = pd.to_datetime(hma_p['dateApproved'], errors='coerce')
hma_p['dateApproved'] = hma_p['dateApproved'].fillna(pd.Timestamp('1900-01-01'))
hma_p['dateApproved_missing'] = hma_p['dateApproved'] == pd.Timestamp('1900-01-01')

hma_p['dateClosed'] = pd.to_datetime(hma_p['dateClosed'], errors='coerce')
hma_p['project_open'] = hma_p['dateClosed'].isna()

hma_p.isna().sum()

Converted the following columns to datetime:
['dateApproved', 'dateClosed']

projectIdentifier               0
programArea                     0
programFy                       0
region                          0
state                           0
stateNumberCode                 0
county                          0
disasterNumber                  0
projectCounties                 0
projectType                     0
status                          0
recipient                       0
recipientTribalIndicator        0
subrecipient                    0
dataSource                      0
dateApproved                    0
dateClosed                  14758
projectAmount                   0
federalShareObligated           0
costSharePercentage             0
benefitCostRatio                0
netValueBenefits                0
numberOfFinalProperties         0
numberOfProperties              0
dateApproved_missing            0
project_open                    0
dtype: int64

In [25]:
hma_p.shape

(44992, 26)

# HMA Project Communities

In [26]:
hma_pc.head()

,projectIdentifier,communityName,communityNumber,hash,lastRefresh,id
0,PDMC-PL-04-AL-2018-005,CRENSHAW COUNTY*,10246,552b5e9801ad882a05fe19ea4b6da6ebd3bc58c0,2024-04-26T14:50:09.105Z,9c66622b-313a-4d2f-84df-b5fe5c822ff3
1,PDMC-PL-04-AL-2016-002,ESCAMBIA COUNTY *,10251,c9339fbd31fcb08f88247e9a055b47be3dee704a,2024-04-26T14:50:09.105Z,6f84d9d4-229a-47b9-b741-ad5ff8ea4a7d
2,PDMC-PL-04-AL-2014-004,"DADEVILLE, CITY OF",10211,35dc3687726fe15ef637433673549cb67f88edb7,2024-04-26T14:50:09.105Z,8a608be3-7a78-4662-9a7c-00fd187d71a2
3,PDMC-MC-10-AK-2009-010,"TANANA, CITY OF",20087,c9629b5cda395bda21435cbb630c4a1b75d986a4,2024-04-26T14:50:09.105Z,022ae712-d54a-43b6-ba66-f6a44bc8fb5e
4,PDMC-TA-10-AK-2005-006,"CORDOVA, CITY OF",20037,9b0cb43d76b6153b5a1ec82b4dd467d0cadda234,2024-04-26T14:50:09.105Z,0706d829-f5e3-4708-b004-d6893c7135f7

In [27]:
hma_pc.isna().sum()

projectIdentifier    0
communityName        0
communityNumber      0
hash                 0
lastRefresh          0
id                   0
dtype: int64

In [28]:
hma_pc.shape

(73077, 6)

In [29]:
# Check if we might be able to merge hma_p and hma_pc
contains_value = 'DR-4251-0005-R' in hma_pc['projectIdentifier'].values
contains_value

True

# Joining Data

In [30]:
# HMA Projects and Communities 

hma_merged = hma_p.merge(hma_pc, on='projectIdentifier', how='left', suffixes=('', '_community'))

hma_merged.head()

,projectIdentifier,programArea,programFy,region,state,stateNumberCode,county,disasterNumber,projectCounties,projectType,...,netValueBenefits,numberOfFinalProperties,numberOfProperties,dateApproved_missing,project_open,communityName,communityNumber,hash,lastRefresh,id
0,DR-4251-0005-R,HMGP,2016,4,Alabama,1,Jackson,4251.0,Jackson,206.2: Safe Room (Tornado and Severe Wind Shel...,...,1012105.0,1,1,False,False,"Woodville, Town Of",10114.0,26cfc3171f72f6c3ffcdb1056af4986f5f2fb34a,2024-04-26T14:50:09.105Z,2efbd6cd-4eeb-46f9-b0a9-92edb81fac0b
1,DR-4214-0018-R,HMGP,2015,1,Massachusetts,25,Norfolk,4214.0,Norfolk,202.2: Elevation of Private Structures - Coastal,...,4008777.0,4,6,False,False,"Weymouth, Town Of",250257.0,fc43c9bf72600b249d4a0c563391a78a78f441c5,2024-04-26T14:50:09.105Z,abf47013-129b-4a5c-8e36-e6c4c504e2a6
2,DR-4283-0027-R,HMGP,2017,4,Florida,12,Flagler,4283.0,Flagler,601.2: Generators - Regular,...,824905.0,0,0,False,True,"PALM COAST, CITY OF",120684.0,e6a4abb273416a7ab4b9690bb4f55b9b7490c1b3,2024-04-26T14:50:09.105Z,9280a6b3-2f46-4e1b-a94b-d2dad6d09594
3,DR-4223-0096,HMGP,2015,6,Texas,48,Jefferson,4223.0,Jefferson,205.2: Retrofitting Public Structures - Wildfire,...,735469.0,0,1,True,True,"Beaumont, City Of",485457.0,a739b3ede52dedba3c3d5e1eb8f477188e3c998e,2024-04-26T14:50:09.105Z,d5ffaa77-4b48-40e3-b2be-5d3701159390
4,DR-4241-0059,HMGP,2016,4,South Carolina,45,Dorchester,4241.0,Dorchester,402.1: Infrastructure Protective Measures (Roa...,...,464354.0,0,0,True,False,Dorchester County *,450068.0,94f09ab308b7b4494adbf20712fdb8dbaaffa301,2024-04-26T14:50:09.105Z,d1d2ba56-c0a0-4fc8-a26a-4a395a5272b1

In [31]:
hma_merged.shape

(61277, 31)

In [32]:
hma_merged.isna().sum()

projectIdentifier               0
programArea                     0
programFy                       0
region                          0
state                           0
stateNumberCode                 0
county                          0
disasterNumber                  0
projectCounties                 0
projectType                     0
status                          0
recipient                       0
recipientTribalIndicator        0
subrecipient                    0
dataSource                      0
dateApproved                    0
dateClosed                  19633
projectAmount                   0
federalShareObligated           0
costSharePercentage             0
benefitCostRatio                0
netValueBenefits                0
numberOfFinalProperties         0
numberOfProperties              0
dateApproved_missing            0
project_open                    0
communityName                7122
communityNumber              7122
hash                         7122
lastRefresh                  7122
id                           7122
dtype: int64

In [33]:
# drop unecessary columns
hma_merged = hma_merged.drop(columns=["hash", "lastRefresh", 'id'])
hma_merged = hma_merged.dropna(subset=['communityName', 'communityNumber'])

hma_merged.isna().sum()

projectIdentifier               0
programArea                     0
programFy                       0
region                          0
state                           0
stateNumberCode                 0
county                          0
disasterNumber                  0
projectCounties                 0
projectType                     0
status                          0
recipient                       0
recipientTribalIndicator        0
subrecipient                    0
dataSource                      0
dateApproved                    0
dateClosed                  18613
projectAmount                   0
federalShareObligated           0
costSharePercentage             0
benefitCostRatio                0
netValueBenefits                0
numberOfFinalProperties         0
numberOfProperties              0
dateApproved_missing            0
project_open                    0
communityName                   0
communityNumber                 0
dtype: int64

In [34]:
# Join HMA and Disasters 
## Standardise joining column 
hma_merged['disasterNumber'] = hma_merged['disasterNumber'].astype('Int64')
disaster_dec['disasterNumber'] = disaster_dec['disasterNumber'].astype('Int64')

## Check if values match 
contains_value = 4251 in hma_merged['disasterNumber'].values
contains_value

True

In [35]:
# merge disasterNumber
hma_dis = hma_merged.merge(disaster_dec, on='disasterNumber', how='left')

hma_dis.head()

,projectIdentifier,programArea,programFy,region_x,state_x,stateNumberCode,county,disasterNumber,projectCounties,projectType,...,tribalRequest,fipsStateCode,fipsCountyCode,placeCode,designatedArea,declarationRequestNumber,incidentId,region_y,hash,id
0,DR-4251-0005-R,HMGP,2016,4,Alabama,1,Jackson,4251,Jackson,206.2: Safe Room (Tornado and Severe Wind Shel...,...,0.0,1.0,1.0,99001.0,Autauga (County),16003.0,2.015122e+09,4.0,dcd4ce6b37ee49875b3f1e32e9a8a16cd6a803d3,5229bbae-eee6-42b8-b277-edbafa8d6cb2
1,DR-4251-0005-R,HMGP,2016,4,Alabama,1,Jackson,4251,Jackson,206.2: Safe Room (Tornado and Severe Wind Shel...,...,0.0,1.0,5.0,99005.0,Barbour (County),16003.0,2.015122e+09,4.0,5b8478f80e09732d1f5195b604b0a3b8ca396a01,2155164c-0c07-4da4-b5d1-d24a831d9bdc
2,DR-4251-0005-R,HMGP,2016,4,Alabama,1,Jackson,4251,Jackson,206.2: Safe Room (Tornado and Severe Wind Shel...,...,0.0,1.0,9.0,99009.0,Blount (County),16003.0,2.015122e+09,4.0,2aeb06b619f8ac8f58c936d883f04b6ba32539dd,2e772244-38aa-4cce-8f9d-cb3cec41a7af
3,DR-4251-0005-R,HMGP,2016,4,Alabama,1,Jackson,4251,Jackson,206.2: Safe Room (Tornado and Severe Wind Shel...,...,0.0,1.0,11.0,99011.0,Bullock (County),16003.0,2.015122e+09,4.0,9e61dc26a6112528d4db9aeabb2aabc18b944590,03312824-daf7-4b58-a88a-ae844d72e6d1
4,DR-4251-0005-R,HMGP,2016,4,Alabama,1,Jackson,4251,Jackson,206.2: Safe Room (Tornado and Severe Wind Shel...,...,0.0,1.0,13.0,99013.0,Butler (County),16003.0,2.015122e+09,4.0,9a77fca608b697db636cda43ba5f47b785e7dff0,e3a71c7d-3351-4ee8-96a6-9f1498237a65

In [36]:
hma_dis.shape

(767875, 52)

In [37]:
hma_dis.isna().sum()

projectIdentifier               0
programArea                     0
programFy                       0
region_x                        0
state_x                         0
stateNumberCode                 0
county                          0
disasterNumber                  0
projectCounties                 0
projectType                     0
status                          0
recipient                       0
recipientTribalIndicator        0
subrecipient                    0
dataSource                      0
dateApproved                    0
dateClosed                  19534
projectAmount                   0
federalShareObligated           0
costSharePercentage             0
benefitCostRatio                0
netValueBenefits                0
numberOfFinalProperties         0
numberOfProperties              0
dateApproved_missing            0
project_open                    0
communityName                   0
communityNumber                 0
femaDeclarationString       31160
state_y                     31160
declarationType             31160
declarationDate             31160
fyDeclared                  31160
incidentType                31160
declarationTitle            31160
ihProgramDeclared           31160
iaProgramDeclared           31160
paProgramDeclared           31160
hmProgramDeclared           31160
incidentBeginDate           31160
incidentEndDate             31160
disasterCloseoutDate        31160
tribalRequest               31160
fipsStateCode               31160
fipsCountyCode              31160
placeCode                   31160
designatedArea              31160
declarationRequestNumber    31160
incidentId                  31160
region_y                    31160
hash                        31160
id                          31160
dtype: int64

In [38]:
# delete unecessary columns
hma_dis = hma_dis.drop(columns=["hash", "id", 'state_y', 'region_y', 'stateNumberCode', 'dataSource','subrecipient', 'recipientTribalIndicator','fyDeclared','fipsStateCode', 'fipsCountyCode','placeCode', 'femaDeclarationString'
])

total_isna = sum(hma_dis.isna().sum())
total_isna

486934

In [39]:
hma_dis.shape

(767875, 39)

In [40]:
# Total missing cells
total_nulls = hma_dis.isna().sum().sum()
print(f"Total missing cells: {total_nulls}")

# Rows with at least one missing value
rows_with_na = hma_dis.isna().any(axis=1).sum()
print(f"Rows with at least one missing value: {rows_with_na}")

Total missing cells: 486934
Rows with at least one missing value: 32127

In [41]:
# check missing values 
hma_dis.isna().sum().sort_values(ascending=False)

incidentId                  31160
hmProgramDeclared           31160
declarationType             31160
declarationDate             31160
incidentType                31160
declarationTitle            31160
ihProgramDeclared           31160
paProgramDeclared           31160
iaProgramDeclared           31160
incidentBeginDate           31160
incidentEndDate             31160
disasterCloseoutDate        31160
tribalRequest               31160
designatedArea              31160
declarationRequestNumber    31160
dateClosed                  19534
dateApproved_missing            0
communityNumber                 0
communityName                   0
project_open                    0
projectIdentifier               0
programArea                     0
numberOfFinalProperties         0
programFy                       0
region_x                        0
state_x                         0
county                          0
disasterNumber                  0
projectCounties                 0
projectType                     0
status                          0
recipient                       0
dateApproved                    0
projectAmount                   0
federalShareObligated           0
costSharePercentage             0
benefitCostRatio                0
netValueBenefits                0
numberOfProperties              0
dtype: int64

In [42]:
# drop null values
hma_dis = hma_dis.dropna(subset=['incidentId'])
hma_dis.isna().sum().sort_values(ascending=False)

dateClosed                  967
projectIdentifier             0
dateApproved_missing          0
communityName                 0
communityNumber               0
declarationType               0
declarationDate               0
incidentType                  0
declarationTitle              0
ihProgramDeclared             0
iaProgramDeclared             0
paProgramDeclared             0
hmProgramDeclared             0
incidentBeginDate             0
incidentEndDate               0
disasterCloseoutDate          0
tribalRequest                 0
designatedArea                0
declarationRequestNumber      0
project_open                  0
numberOfProperties            0
programArea                   0
numberOfFinalProperties       0
programFy                     0
region_x                      0
state_x                       0
county                        0
disasterNumber                0
projectCounties               0
projectType                   0
status                        0
recipient                     0
dateApproved                  0
projectAmount                 0
federalShareObligated         0
costSharePercentage           0
benefitCostRatio              0
netValueBenefits              0
incidentId                    0
dtype: int64

In [43]:
hma_dis.shape

(736715, 39)

In [44]:
# Joining Black Homeowners Data 
bh = black_homeowners.copy()

# Split 'geo_name' into county and state
bh[['county', 'state']] = bh['geo_name'].str.replace(" County", "", regex=False)\
                                        .str.replace(" Parish", "", regex=False)\
                                        .str.split(", ", expand=True)

# Make sure formatting matches HMA dataset
bh['county'] = bh['county'].str.strip()
bh['state'] = bh['state'].str.strip()

bh.head()

,geo_level,geo_name,year,state_name,pct_black_alone,pct_owner_occupied_black_alone,rpl_themes,quartiles_rpl_themes,county,state
0,county,"Barbour County, West Virginia",2023,West Virginia,1.8,0.0,0.456,26-50% of geographies,Barbour,West Virginia
1,county,"Alexander County, North Carolina",2023,North Carolina,4.0,2.0,0.456,26-50% of geographies,Alexander,North Carolina
2,county,"Jackson County, Indiana",2023,Indiana,1.1,0.4,0.456,26-50% of geographies,Jackson,Indiana
3,county,"York County, South Carolina",2023,South Carolina,18.7,13.0,0.344,26-50% of geographies,York,South Carolina
4,county,"Clinton County, Indiana",2023,Indiana,0.7,0.0,0.344,26-50% of geographies,Clinton,Indiana

In [45]:
# Formatting features to join 

# Clean both datasets

hma_dis['state_x'] = hma_dis['state_x'].str.upper().str.strip()
hma_dis['county'] = hma_dis['county'].str.upper().str.strip().str.replace(" COUNTY", "").str.replace(" PARISH", "")

bh['state'] = bh['state'].str.upper().str.strip()
bh['county'] = bh['county'].str.upper().str.strip().str.replace(" COUNTY", "").str.replace(" PARISH", "")

In [46]:

# Then merge
df_final = hma_dis.merge(
    bh,
    left_on=['state_x', 'county'],
    right_on=['state', 'county'],
    how='left'
)

In [47]:
df_final.isna().sum().sort_values(ascending=False)

state                             92182
geo_level                         92182
quartiles_rpl_themes              92182
rpl_themes                        92182
pct_owner_occupied_black_alone    92182
pct_black_alone                   92182
state_name                        92182
year                              92182
geo_name                          92182
dateClosed                          967
incidentId                            0
declarationRequestNumber              0
declarationDate                       0
designatedArea                        0
tribalRequest                         0
disasterCloseoutDate                  0
incidentEndDate                       0
incidentBeginDate                     0
hmProgramDeclared                     0
paProgramDeclared                     0
iaProgramDeclared                     0
ihProgramDeclared                     0
declarationTitle                      0
incidentType                          0
projectIdentifier                     0
programArea                           0
dateApproved                          0
programFy                             0
region_x                              0
state_x                               0
county                                0
disasterNumber                        0
projectCounties                       0
projectType                           0
status                                0
recipient                             0
projectAmount                         0
communityNumber                       0
federalShareObligated                 0
costSharePercentage                   0
benefitCostRatio                      0
netValueBenefits                      0
numberOfFinalProperties               0
numberOfProperties                    0
dateApproved_missing                  0
project_open                          0
communityName                         0
declarationType                       0
dtype: int64

In [48]:
df = df_final[df_final['pct_black_alone'].notna()].copy()
df

,projectIdentifier,programArea,programFy,region_x,state_x,county,disasterNumber,projectCounties,projectType,status,...,incidentId,geo_level,geo_name,year,state_name,pct_black_alone,pct_owner_occupied_black_alone,rpl_themes,quartiles_rpl_themes,state
0,DR-4251-0005-R,HMGP,2016,4,ALABAMA,JACKSON,4251,Jackson,206.2: Safe Room (Tornado and Severe Wind Shel...,Closed,...,2.015122e+09,county,"Jackson County, Alabama",2023.0,Alabama,3.0,2.3,0.719,51-75% of geographies,ALABAMA
1,DR-4251-0005-R,HMGP,2016,4,ALABAMA,JACKSON,4251,Jackson,206.2: Safe Room (Tornado and Severe Wind Shel...,Closed,...,2.015122e+09,county,"Jackson County, Alabama",2023.0,Alabama,3.0,2.3,0.719,51-75% of geographies,ALABAMA
2,DR-4251-0005-R,HMGP,2016,4,ALABAMA,JACKSON,4251,Jackson,206.2: Safe Room (Tornado and Severe Wind Shel...,Closed,...,2.015122e+09,county,"Jackson County, Alabama",2023.0,Alabama,3.0,2.3,0.719,51-75% of geographies,ALABAMA
3,DR-4251-0005-R,HMGP,2016,4,ALABAMA,JACKSON,4251,Jackson,206.2: Safe Room (Tornado and Severe Wind Shel...,Closed,...,2.015122e+09,county,"Jackson County, Alabama",2023.0,Alabama,3.0,2.3,0.719,51-75% of geographies,ALABAMA
4,DR-4251-0005-R,HMGP,2016,4,ALABAMA,JACKSON,4251,Jackson,206.2: Safe Room (Tornado and Severe Wind Shel...,Closed,...,2.015122e+09,county,"Jackson County, Alabama",2023.0,Alabama,3.0,2.3,0.719,51-75% of geographies,ALABAMA
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
736710,DR-1459-0007-R,HMGP,2003,4,MISSISSIPPI,LAMAR,1459,Lamar,200.3: Acquisition of Public Real Property (St...,Closed,...,2.003041e+09,county,"Lamar County, Mississippi",2023.0,Mississippi,21.6,11.2,0.603,51-75% of geographies,MISSISSIPPI
736711,DR-1459-0007-R,HMGP,2003,4,MISSISSIPPI,LAMAR,1459,Lamar,200.3: Acquisition of Public Real Property (St...,Closed,...,2.003041e+09,county,"Lamar County, Mississippi",2023.0,Mississippi,21.6,11.2,0.603,51-75% of geographies,MISSISSIPPI
736712,DR-1459-0007-R,HMGP,2003,4,MISSISSIPPI,LAMAR,1459,Lamar,200.3: Acquisition of Public Real Property (St...,Closed,...,2.003041e+09,county,"Lamar County, Mississippi",2023.0,Mississippi,21.6,11.2,0.603,51-75% of geographies,MISSISSIPPI
736713,DR-1459-0007-R,HMGP,2003,4,MISSISSIPPI,LAMAR,1459,Lamar,200.3: Acquisition of Public Real Property (St...,Closed,...,2.003041e+09,county,"Lamar County, Mississippi",2023.0,Mississippi,21.6,11.2,0.603,51-75% of geographies,MISSISSIPPI
736714,DR-1459-0007-R,HMGP,2003,4,MISSISSIPPI,LAMAR,1459,Lamar,200.3: Acquisition of Public Real Property (St...,Closed,...,2.003041e+09,county,"Lamar County, Mississippi",2023.0,Mississippi,21.6,11.2,0.603,51-75% of geographies,MISSISSIPPI

In [49]:
df.isna().sum()

projectIdentifier                   0
programArea                         0
programFy                           0
region_x                            0
state_x                             0
county                              0
disasterNumber                      0
projectCounties                     0
projectType                         0
status                              0
recipient                           0
dateApproved                        0
dateClosed                        860
projectAmount                       0
federalShareObligated               0
costSharePercentage                 0
benefitCostRatio                    0
netValueBenefits                    0
numberOfFinalProperties             0
numberOfProperties                  0
dateApproved_missing                0
project_open                        0
communityName                       0
communityNumber                     0
declarationType                     0
declarationDate                     0
incidentType                        0
declarationTitle                    0
ihProgramDeclared                   0
iaProgramDeclared                   0
paProgramDeclared                   0
hmProgramDeclared                   0
incidentBeginDate                   0
incidentEndDate                     0
disasterCloseoutDate                0
tribalRequest                       0
designatedArea                      0
declarationRequestNumber            0
incidentId                          0
geo_level                           0
geo_name                            0
year                                0
state_name                          0
pct_black_alone                     0
pct_owner_occupied_black_alone      0
rpl_themes                          0
quartiles_rpl_themes                0
state                               0
dtype: int64

In [50]:
df.shape

(644533, 48)

In [51]:
print("Rows with race data:", df_final['pct_black_alone'].notna().sum())
print("Total rows in df_final:", df_final.shape[0])

Rows with race data: 644533
Total rows in df_final: 736715

In [ ]:
df.to_csv('/Users/marcelamarquesbicalho/github/bwdc-project/equity_dataset.csv', index=False)